version: "3.8"

services:
  evolution_api:
    image: atendai/evolution-api:v1.6.1
    command: ["node", "./dist/src/main.js"]
    networks:
      - app_network
    volumes:
      - eapi_instances:/evolution/instances
      - eapi_store:/evolution/store
    environment:
      SERVER_URL: http://localhost:8080
      CONFIG_SESSION_PHONE_CLIENT: evolution-api-pedroaf0
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_API_KEY: 9f2D63MgSgmoiaJEqC8XZh0R4Bgm3CtSKCXtnHCw0zk67ifcaNyseg5BnNiPIKzx55lSlO8YgpBxWAeaT4UIWFycyGCV85lokCtcRNU0YPVKGSdeEqlwVifTgDqY4a7D
      # Permanent data storage MongoDB
      DATABASE_ENABLED: false
      DATABASE_CONNECTION_URI: mongodb://USER:PASSWORD@HOSTNAME:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
      DATABASE_CONNECTION_DB_PREFIX_NAME: evdocker
      # Choose the data you want to save in the application's database or store
      DATABASE_SAVE_DATA_INSTANCE: "true"
      DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
      DATABASE_SAVE_MESSAGE_UPDATE: "false"
      DATABASE_SAVE_DATA_CONTACTS: "false"
      DATABASE_SAVE_DATA_CHATS: "false"
      #logs definição
      LOG_LEVEL: ERROR,WARN
      # config adicional
      DEL_INSTANCE: "false"
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"
    ports:
      - 8080:8080

networks:
  app_network:
    external: true

volumes:
  eapi_instances:
    external: true
  eapi_store:
    external: true
